### ISSUE TITLE
Vulnerable just-extend dependency

### ISSUE THREAD

**Issue by farkasmate** [ITV/pmpact#4]
The issue: https://github.com/ITV/pmpact/network/alert/package-lock.json/just-extend/open

Please consider updating `"sinon": "6.1.5"` to `"sinon": "7.2.3"` (major version change):
https://github.com/ITV/pmpact/blob/master/package.json#L43

**Comment by julio-alves** [comment]
Updated `sinon` to `7.2.3`.

**Comment by julio-alves** [comment]
Published `v0.2.1` to npm.
